<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TeacherSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
       $teachers = [
    [
        'name' => 'Ram Sharma',
        'email' => 'ram.sharma1@example.com',
        'phone' => '9800000001',
        'address' => 'Kathmandu',
        'subject_specialization' => 'Mathematics',
        'status' => 'active',
        'joining_date' => '2018-04-12',
        'leaving_date' => null,
        'qualification' => 'MSc Mathematics',
        'field1' => null,
        'created_by' => 1,
        'is_active' => 1,
        'date_of_birth' => '1985-06-15',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'name' => 'Sita Koirala',
        'email' => 'sita.koirala2@example.com',
        'phone' => '9800000002',
        'address' => 'Lalitpur',
        'subject_specialization' => 'English',
        'status' => 'active',
        'joining_date' => '2019-07-01',
        'leaving_date' => null,
        'qualification' => 'MA English',
        'field1' => null,
        'created_by' => 1,
        'is_active' => 1,
        'date_of_birth' => '1990-02-20',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'name' => 'Hari Prasad',
        'email' => 'hari.prasad3@example.com',
        'phone' => '9800000003',
        'address' => 'Bhaktapur',
        'subject_specialization' => 'Science',
        'status' => 'on_leave',
        'joining_date' => '2017-03-15',
        'leaving_date' => null,
        'qualification' => 'BSc Physics',
        'field1' => null,
        'created_by' => 1,
        'is_active' => 1,
        'date_of_birth' => '1982-09-10',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'name' => 'Anita Thapa',
        'email' => 'anita.thapa4@example.com',
        'phone' => '9800000004',
        'address' => 'Pokhara',
        'subject_specialization' => 'Social Studies',
        'status' => 'active',
        'joining_date' => '2020-01-10',
        'leaving_date' => null,
        'qualification' => 'MA Sociology',
        'field1' => null,
        'created_by' => 1,
        'is_active' => 1,
        'date_of_birth' => '1992-11-05',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'name' => 'Kiran Adhikari',
        'email' => 'kiran.adhikari5@example.com',
        'phone' => '9800000005',
        'address' => 'Chitwan',
        'subject_specialization' => 'Computer',
        'status' => 'active',
        'joining_date' => '2021-06-18',
        'leaving_date' => null,
        'qualification' => 'BSc CSIT',
        'field1' => null,
        'created_by' => 1,
        'is_active' => 1,
        'date_of_birth' => '1995-03-25',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'name' => 'Maya Gurung',
        'email' => 'maya.gurung6@example.com',
        'phone' => '9800000006',
        'address' => 'Lamjung',
        'subject_specialization' => 'Nepali',
        'status' => 'resigned',
        'joining_date' => '2016-02-11',
        'leaving_date' => '2022-05-30',
        'qualification' => 'MA Nepali',
        'field1' => null,
        'created_by' => 1,
        'is_active' => 0,
        'date_of_birth' => '1980-07-12',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'name' => 'Suman KC',
        'email' => 'suman.kc7@example.com',
        'phone' => '9800000007',
        'address' => 'Dang',
        'subject_specialization' => 'Account',
        'status' => 'active',
        'joining_date' => '2019-09-09',
        'leaving_date' => null,
        'qualification' => 'BBS',
        'field1' => null,
        'created_by' => 1,
        'is_active' => 1,
        'date_of_birth' => '1988-12-01',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'name' => 'Rita Rai',
        'email' => 'rita.rai8@example.com',
        'phone' => '9800000008',
        'address' => 'Ilam',
        'subject_specialization' => 'Biology',
        'status' => 'active',
        'joining_date' => '2018-08-21',
        'leaving_date' => null,
        'qualification' => 'MSc Biology',
        'field1' => null,
        'created_by' => 1,
        'is_active' => 1,
        'date_of_birth' => '1991-04-18',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'name' => 'Dipak Bhandari',
        'email' => 'dipak.bhandari9@example.com',
        'phone' => '9800000009',
        'address' => 'Butwal',
        'subject_specialization' => 'Chemistry',
        'status' => 'on_leave',
        'joining_date' => '2015-05-05',
        'leaving_date' => null,
        'qualification' => 'MSc Chemistry',
        'field1' => null,
        'created_by' => 1,
        'is_active' => 1,
        'date_of_birth' => '1983-01-14',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'name' => 'Sunita Shrestha',
        'email' => 'sunita.shrestha10@example.com',
        'phone' => '9800000010',
        'address' => 'Kathmandu',
        'subject_specialization' => 'Economics',
        'status' => 'active',
        'joining_date' => '2022-02-02',
        'leaving_date' => null,
        'qualification' => 'MA Economics',
        'field1' => null,
        'created_by' => 1,
        'is_active' => 1,
        'date_of_birth' => '1996-06-06',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'name' => 'Subash Chaudhary',
        'email' => 'subash.chaudhary11@example.com',
        'phone' => '9800000011',
        'address' => 'Kathmandu',
        'subject_specialization' => 'Commerce',
        'status' => 'active',
        'joining_date' => '2022-02-02',
        'leaving_date' => null,
        'qualification' => 'MA Commerce',
        'field1' => null,
        'created_by' => 1,
        'is_active' => 1,
        'date_of_birth' => '1993-02-06',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'name' => 'Sharmila Dangol',
        'email' => 'sharmila.dangol12@example.com',
        'phone' => '9800000012',
        'address' => 'Kathmandu',
        'subject_specialization' => 'Art',
        'status' => 'active',
        'joining_date' => '2022-02-02',
        'leaving_date' => null,
        'qualification' => 'MA Art',
        'field1' => null,
        'created_by' => 1,
        'is_active' => 1,
        'date_of_birth' => '1986-07-06',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'name' => 'Abina Sharma',
        'email' => 'abina.sharma13@example.com',
        'phone' => '9800000013',
        'address' => 'Kathmandu',
        'subject_specialization' => 'Science',
        'status' => 'active',
        'joining_date' => '2022-02-02',
        'leaving_date' => null,
        'qualification' => 'MA Science',
        'field1' => null,
        'created_by' => 1,
        'is_active' => 1,
        'date_of_birth' => '1996-06-06',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'name' => 'Jharana Oli',
        'email' => 'jharana.oli14@example.com',
        'phone' => '9800000014',
        'address' => 'Kathmandu',
        'subject_specialization' => 'Nepali',
        'status' => 'active',
        'joining_date' => '2022-02-02',
        'leaving_date' => null,
        'qualification' => 'MA Economics',
        'field1' => null,
        'created_by' => 1,
        'is_active' => 1,
        'date_of_birth' => '1996-06-06',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'name' => 'Thaneshwor Neupane',
        'email' => 'thaneshwor.neupane15@example.com',
        'phone' => '9800000015',
        'address' => 'Kathmandu',
        'subject_specialization' => 'English',
        'status' => 'active',
        'joining_date' => '2022-02-02',
        'leaving_date' => null,
        'qualification' => 'MA English',
        'field1' => null,
        'created_by' => 1,
        'is_active' => 1,
        'date_of_birth' => '1996-06-06',
        'created_at' => now(),
        'updated_at' => now(),
    ],
];

        DB::table('tbl_teachers')->insert($teachers);
    }
}
