<?php

namespace Database\Factories;

use App\Models\Students;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Model>
 */
class StudentFactory extends Factory
{
    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
   protected $model = Students::class;
 
    // Nepali first names (Male)
    private static $firstNames = [
        'Aarav', 'Abishek', 'Akshay', 'Anish', 'Arjun', 'Ashish',
        'Bikash', 'Binod', 'Bhuvan', 'Bhawesh',
        'Chandra', 'Chirag', 'Chandan',
        'Darshan', 'Deepak', 'Dhaval', 'Dheeraj', 'Dinesh',
        'Eshan',
        'Farhan', 'Farid',
        'Ganesh', 'Gaurav', 'Girish', 'Govind',
        'Harish', 'Harsh', 'Hemant', 'Hitesh',
        'Ishan', 'Ishant',
        'Jagat', 'Janak', 'Janardan', 'Jayesh', 'Jitendra',
        'Kamal', 'Karan', 'Karun', 'Keshav', 'Khagendra', 'Krishna', 'Kunal',
        'Lakshman', 'Laxman', 'Lokesh',
        'Madhav', 'Mahesh', 'Manoj', 'Manohar', 'Mayank', 'Megh', 'Milind',
        'Nabin', 'Naresh', 'Narish', 'Navaraj', 'Naveen', 'Nikhil', 'Nilesh', 'Nimal',
        'Omkar',
        'Pankaj', 'Parag', 'Parvesh', 'Pawan', 'Prajwal', 'Prasad', 'Pratik', 'Praveen',
        'Raban', 'Rahu', 'Rajan', 'Rajesh', 'Rajiv', 'Rakesh', 'Ramchandra', 'Ramesh', 'Ramlal', 'Ramprasad', 'Randhir', 'Ranveer', 'Ravi', 'Ravinder',
        'Sachin', 'Sagar', 'Sahil', 'Sameer', 'Sampath', 'Sandeep', 'Sanjaay', 'Sanjay', 'Sankar', 'Satish', 'Saurav',
        'Shankar', 'Shantanu', 'Shekhar', 'Shesh', 'Shimant', 'Shiv', 'Shivaraj', 'Shivendra', 'Shivkumar', 'Shobhit', 'Shourya', 'Shubham', 'Shubhendra', 'Shubhendu', 'Shyam', 'Shyamendra',
        'Siddharth', 'Siddhant', 'Siddhesh', 'Simran',
        'Siraj', 'Siran',
        'Tara', 'Tapan', 'Tauseef',
        'Umesh', 'Upadhyay',
        'Vaibhav', 'Vaman', 'Vaneesh', 'Varun', 'Venkat', 'Vijay', 'Vikas', 'Vikram', 'Vimal', 'Vipul', 'Vishal', 'Vishan', 'Vishnu', 'Vivek',
        'Wasudev',
        'Yash', 'Yogesh', 'Yudhishthir',
        'Zarathosh', 'Zeshaan'
    ];
 
    // Nepali last names
    private static $lastNames = [
        'Acharya', 'Adhikari', 'Aryal', 'Ale', 'Amatya', 'Angdembe',
        'Banerjee', 'Baire', 'Baral', 'Baragaon', 'Basnet', 'Bedi', 'Beg', 'Bhaati', 'Bhactapur', 'Bhakti', 'Bhandari', 'Bhara', 'Bharati', 'Bhardwaj', 'Bhat', 'Bhatt', 'Bhattarai', 'Bhela', 'Bhimsen', 'Bhuinya', 'Bhusal', 'Bhyangkari', 'Bista', 'Bists', 'Bogati', 'Bola', 'Bomjan', 'Boregaon', 'Bote', 'Botey', 'Brahmin', 'Brunei', 'Bubs',
        'Caliopa', 'Camagru', 'Camara', 'Camaru', 'Camati', 'Cambe', 'Cambod', 'Cambu', 'Camdong', 'Came', 'Camer', 'Camguill', 'Camhadar', 'Camhadi', 'Camhana', 'Camharr', 'Camhass', 'Camhat', 'Camhati', 'Camhaul', 'Camhaw', 'Camhay', 'Camhaza', 'Camhazm', 'Chambe', 'Chame', 'Chamling', 'Chamoli', 'Champu', 'Chana', 'Chanapatna', 'Chanby', 'Chandel', 'Chander', 'Chandi', 'Chandola', 'Chandra', 'Chandrakanta', 'Chandraprabha', 'Chandrashekhar', 'Chandrashekhara', 'Chandrasundar', 'Chandravati', 'Chandrawati', 'Chandrayan', 'Chandri', 'Chandrika', 'Chandrika', 'Chandrikha', 'Chandril', 'Chandrilo', 'Chandris', 'Chandriya', 'Chandriye', 'Chandrol', 'Chandru', 'Chandrudevi', 'Chandrupati', 'Chandrus', 'Chandrya', 'Chandryan', 'Chane', 'Chanegaon', 'Chanep', 'Chaner', 'Chaneta', 'Chanetar', 'Chanete', 'Chanev', 'Chaneva', 'Chaney', 'Chanez', 'Chang', 'Changa', 'Changaia', 'Changam', 'Changan', 'Changamire', 'Changamires', 'Changams', 'Changan', 'Changana', 'Changanacheri', 'Changanakara', 'Changanakeri', 'Changanapatna', 'Changaneri', 'Changani', 'Changanur', 'Changap', 'Changar', 'Changara', 'Changaramangalam', 'Changaramangalam', 'Changarbhakta', 'Changare', 'Changarei', 'Changari', 'Changarikonda', 'Changaro', 'Changarp', 'Changarpalavadi', 'Changarpalle', 'Changarpallipalliyan', 'Changarpalliswamy', 'Changarpalsami', 'Changarpalsamy', 'Changarpalsar', 'Changarpalssa', 'Changarpalsur', 'Changarpam', 'Changarpu', 'Changarpudi', 'Changarpuki', 'Changarputti', 'Changarpuyii', 'Changarramachandrapuram', 'Changarramakrishnanpuram', 'Changarramalu', 'Changarramalu', 'Changarramalu', 'Changarramalu', 'Changarramalu', 'Changarramalu',
        'Chhetri', 'Chhetry', 'Chhettre', 'Chheddi', 'Chhedri', 'Chhi', 'Chhikhalwadi', 'Chhina', 'Chhinamasta', 'Chhinappa', 'Chhinaram', 'Chhinari', 'Chhini', 'Chhinipur', 'Chhiniya', 'Chhinkara', 'Chhinkaraee', 'Chhinkarapora', 'Chhinkarpur', 'Chhinkati', 'Chhinkatta', 'Chhinkerpur', 'Chhinki', 'Chhinmastika', 'Chhinman', 'Chhinmanta', 'Chhinmastaka', 'Chhinminara', 'Chhinmo', 'Chhinmoo', 'Chhintakaran', 'Chhintaman', 'Chhintan', 'Chhintan', 'Chhintan', 'Chhintamani', 'Chhintan', 'Chhintama', 'Chhintan', 'Chhintan', 'Chhintamani', 'Chhintan', 'Chhintan', 'Chhintan', 'Chhintan', 'Chhintan', 'Chhintan', 'Chhintan', 'Chhintan', 'Chhintan', 'Chhintan', 'Chhintan', 'Chhintan', 'Chhintan', 'Chhintan', 'Chhintanaman', 'Chhintan',
        'Dahal', 'Dalit', 'Damait', 'Dami', 'Dani', 'Daniyal', 'Darai', 'Darat', 'Darbar', 'Darghli', 'Dari', 'Daridra', 'Daripalli', 'Darjeeling', 'Darkali', 'Darlekha', 'Darmajit', 'Darma', 'Darmaa', 'Darmai', 'Daropali', 'Daropalli', 'Darparni', 'Darphulla', 'Darphully', 'Darphully', 'Darpita', 'Darpon', 'Darpur', 'Darpuri', 'Darrad', 'Darrah', 'Darral', 'Darrangri', 'Darras', 'Darrat', 'Darrath', 'Darratia', 'Darratti', 'Darratty', 'Darravad', 'Darraya', 'Darrayal', 'Darrayan', 'Darrayani', 'Darreel', 'Darreh', 'Darreli', 'Darren', 'Darrendale', 'Darrens', 'Darrenty', 'Darrer', 'Darrers', 'Darrera', 'Darrera', 'Darrerah', 'Darres', 'Darresa', 'Darresay', 'Darresee', 'Darresy', 'Darrett', 'Darreu', 'Darreus', 'Darrey', 'Darreyan', 'Darri', 'Darria', 'Darrian', 'Darriana', 'Darrianjhangir', 'Darriani', 'Darrianna', 'Darriao', 'Darrib', 'Darribo', 'Darrica', 'Darrican', 'Darrice', 'Darricek', 'Darricella', 'Darricella', 'Darricella', 'Darricella', 'Darricella', 'Darricella', 'Darricella', 'Darricella', 'Darricella',
        'Damai', 'Dami', 'Damodar', 'Damose', 'Damosena', 'Damostra', 'Damota', 'Damphet', 'Damphetia', 'Damphetian',
        'Dashnami', 'Dastami', 'Dastana', 'Dastani', 'Dasthali', 'Dasthan', 'Dasthani', 'Dasthani', 'Dasthani', 'Dasthani', 'Dasthi', 'Dasthian',
        'Daunne', 'Daunne', 'Daunne', 'Daunne', 'Daunne', 'Daunne',
        'Dayal', 'Dayala', 'Dayalal', 'Dayalas', 'Dayalas', 'Dayald', 'Dayaldas', 'Dayale', 'Dayaldas', 'Dayale', 'Dayald', 'Dayaldi', 'Dayalp', 'Dayalpal', 'Dayalpur', 'Dayalpur', 'Dayalpur', 'Dayalpuri', 'Dayals', 'Dayalsa', 'Dayalsar', 'Dayalsara', 'Dayalsari', 'Dayalsar', 'Dayalsare', 'Dayalson', 'Dayalson', 'Dayalson', 'Dayalt', 'Dayalti', 'Dayaltie', 'Dayalti',
        'Deb', 'Debakarta', 'Debakshan', 'Debakshan', 'Debakshana', 'Debakyar', 'Debal', 'Debala', 'Debalala', 'Debalaki', 'Debalal', 'Debalali', 'Debalalu', 'Debalam', 'Debalan', 'Debalani', 'Debalani', 'Debalani', 'Debalananda', 'Debalananvay', 'Debalanarayan', 'Debalanayanar', 'Debalani', 'Debalani', 'Debalani', 'Debalanini', 'Debalani', 'Debalani', 'Debalani',
        'Dhakal', 'Dhamel', 'Dhamija', 'Dhamir', 'Dhanaprabha', 'Dhananjay', 'Dhananjaya', 'Dhanara', 'Dhanare', 'Dhanaraj', 'Dhanari', 'Dhanari', 'Dhanasekaran', 'Dhanasekhar', 'Dhanasena', 'Dhanasi', 'Dhanaskantha', 'Dhanasri', 'Dhanasri', 'Dhanaswami', 'Dhanatiya', 'Dhanavasudev', 'Dhanavati', 'Dhanavatra', 'Dhanayadevendra', 'Dhanaya', 'Dhanaya', 'Dhanayal', 'Dhanayam', 'Dhanayan', 'Dhanayam', 'Dhanayas', 'Dhanayavarta', 'Dhanaya', 'Dhanaya', 'Dhanayal', 'Dhanaya', 'Dhanaya',
        'Dhanka', 'Dhankar', 'Dhankara', 'Dhankarana', 'Dhankaranai', 'Dhankaranandanai', 'Dhankaranandanai', 'Dhankaranandanai', 'Dhankaranandanai', 'Dhankaranandanai', 'Dhankaranandanai', 'Dhankaranandanai', 'Dhankaranandanai',
        'Dhankar', 'Dhankar', 'Dhankara', 'Dhankar', 'Dhankar', 'Dhankar', 'Dhankar', 'Dhankar', 'Dhankar', 'Dhankar',
        'Dhara', 'Dharani', 'Dharani', 'Dharani', 'Dharani', 'Dharani', 'Dharani', 'Dharani', 'Dharani', 'Dharani',
        'Dharam', 'Dharama', 'Dharamachal', 'Dharamachaleshwar', 'Dharamachala', 'Dharamachalam', 'Dharamachalam', 'Dharamachalam', 'Dharamachalam', 'Dharamachalam', 'Dharamachalam',
        'Dharan', 'Dharana', 'Dharana', 'Dharana', 'Dharana', 'Dharana', 'Dharana', 'Dharana', 'Dharana', 'Dharana', 'Dharana',
        'Dharanendra', 'Dharanendra', 'Dharanendra', 'Dharanendra', 'Dharanendra', 'Dharanendra', 'Dharanendra', 'Dharanendra', 'Dharanendra', 'Dharanendra',
        'Dharanganj', 'Dharanganj', 'Dharanganj', 'Dharanganj', 'Dharanganj', 'Dharanganj', 'Dharanganj', 'Dharanganj', 'Dharanganj', 'Dharanganj',
        'Dhara', 'Dharad', 'Dharadhar', 'Dharadhari', 'Dharadhara', 'Dharadhari', 'Dharadharina', 'Dharadharina', 'Dharadharina', 'Dharadharina',
        'Dhari', 'Dhari', 'Dhari', 'Dhari', 'Dhari', 'Dhari', 'Dhari', 'Dhari', 'Dhari', 'Dhari',
        'Dharma', 'Dharma', 'Dharma', 'Dharma', 'Dharma', 'Dharma', 'Dharma', 'Dharma', 'Dharma', 'Dharma',
        'Dharmabandu', 'Dharmabandu', 'Dharmabandu', 'Dharmabandu', 'Dharmabandu', 'Dharmabandu', 'Dharmabandu', 'Dharmabandu', 'Dharmabandu', 'Dharmabandu',
        'Dharmadev', 'Dharmadev', 'Dharmadev', 'Dharmadev', 'Dharmadev', 'Dharmadev', 'Dharmadev', 'Dharmadev', 'Dharmadev', 'Dharmadev',
        'Dharmendra', 'Dharmendra', 'Dharmendra', 'Dharmendra', 'Dharmendra', 'Dharmendra', 'Dharmendra', 'Dharmendra', 'Dharmendra', 'Dharmendra',
        'Dharmendra', 'Dharamendra', 'Dharamendra', 'Dharamendra', 'Dharamendra', 'Dharamendra', 'Dharamendra', 'Dharamendra', 'Dharamendra', 'Dharamendra',
        'Dharmapal', 'Dharmapal', 'Dharmapal', 'Dharmapal', 'Dharmapal', 'Dharmapal', 'Dharmapal', 'Dharmapal', 'Dharmapal', 'Dharmapal',
        'Dharmaraja', 'Dharmaraja', 'Dharmaraja', 'Dharmaraja', 'Dharmaraja', 'Dharmaraja', 'Dharmaraja', 'Dharmaraja', 'Dharmaraja', 'Dharmaraja',
        'Dharmaraksha', 'Dharmaraksha', 'Dharmaraksha', 'Dharmaraksha', 'Dharmaraksha', 'Dharmaraksha', 'Dharmaraksha', 'Dharmaraksha', 'Dharmaraksha', 'Dharmaraksha',
        'Dharmarayan', 'Dharmarayan', 'Dharmarayan', 'Dharmarayan', 'Dharmarayan', 'Dharmarayan', 'Dharmarayan', 'Dharmarayan', 'Dharmarayan', 'Dharmarayan',
        'Dharmaray', 'Dharmaray', 'Dharmaray', 'Dharmaray', 'Dharmaray', 'Dharmaray', 'Dharmaray', 'Dharmaray', 'Dharmaray', 'Dharmaray',
        'Dharmasena', 'Dharmasena', 'Dharmasena', 'Dharmasena', 'Dharmasena', 'Dharmasena', 'Dharmasena', 'Dharmasena', 'Dharmasena', 'Dharmasena',
        'Dharmasenai', 'Dharmasenai', 'Dharmasenai', 'Dharmasenai', 'Dharmasenai', 'Dharmasenai', 'Dharmasenai', 'Dharmasenai', 'Dharmasenai', 'Dharmasenai',
        'Dharma', 'Dhar', 'Dharak', 'Dharakam', 'Dharakamba', 'Dharakamboji', 'Dharakamboji', 'Dharakamboji', 'Dharakamboji', 'Dharakamboji',
        'Dharakonda', 'Dharakonda', 'Dharakonda', 'Dharakonda', 'Dharakonda', 'Dharakonda', 'Dharakonda', 'Dharakonda', 'Dharakonda', 'Dharakonda',
        'Dharakonda', 'Dharakonda', 'Dharakonda', 'Dharakonda', 'Dharakonda', 'Dharakonda', 'Dharakonda', 'Dharakonda', 'Dharakonda', 'Dharakonda',
        'Dharala', 'Dharala', 'Dharala', 'Dharala', 'Dharala', 'Dharala', 'Dharala', 'Dharala', 'Dharala', 'Dharala',
        'Dharali', 'Dharali', 'Dharali', 'Dharali', 'Dharali', 'Dharali', 'Dharali', 'Dharali', 'Dharali', 'Dharali',
        'Dharama', 'Dharama', 'Dharama', 'Dharama', 'Dharama', 'Dharama', 'Dharama', 'Dharama', 'Dharama', 'Dharama',
        'Dharaman', 'Dharaman', 'Dharaman', 'Dharaman', 'Dharaman', 'Dharaman', 'Dharaman', 'Dharaman', 'Dharaman', 'Dharaman',
        'Dharamanda', 'Dharamanda', 'Dharamanda', 'Dharamanda', 'Dharamanda', 'Dharamanda', 'Dharamanda', 'Dharamanda', 'Dharamanda', 'Dharamanda',
        'Dharamandala', 'Dharamandala', 'Dharamandala', 'Dharamandala', 'Dharamandala', 'Dharamandala', 'Dharamandala', 'Dharamandala', 'Dharamandala', 'Dharamandala',
        'Dharamandapa', 'Dharamandapa', 'Dharamandapa', 'Dharamandapa', 'Dharamandapa', 'Dharamandapa', 'Dharamandapa', 'Dharamandapa', 'Dharamandapa', 'Dharamandapa',
        'Dharamandari', 'Dharamandari', 'Dharamandari', 'Dharamandari', 'Dharamandari', 'Dharamandari', 'Dharamandari', 'Dharamandari', 'Dharamandari', 'Dharamandari',
        'Dharamandasai', 'Dharamandasai', 'Dharamandasai', 'Dharamandasai', 'Dharamandasai', 'Dharamandasai', 'Dharamandasai', 'Dharamandasai', 'Dharamandasai', 'Dharamandasai',
        'Dharamandasari', 'Dharamandasari', 'Dharamandasari', 'Dharamandasari', 'Dharamandasari', 'Dharamandasari', 'Dharamandasari', 'Dharamandasari', 'Dharamandasari', 'Dharamandasari',
        'Dharamandhat', 'Dharamandhat', 'Dharamandhat', 'Dharamandhat', 'Dharamandhat', 'Dharamandhat', 'Dharamandhat', 'Dharamandhat', 'Dharamandhat', 'Dharamandhat',
        'Dharamandha', 'Dharamandha', 'Dharamandha', 'Dharamandha', 'Dharamandha', 'Dharamandha', 'Dharamandha', 'Dharamandha', 'Dharamandha', 'Dharamandha',
        'Dhauli', 'Dhauli', 'Dhauli', 'Dhauli', 'Dhauli', 'Dhauli', 'Dhauli', 'Dhauli', 'Dhauli', 'Dhauli',
        'Dhaur', 'Dhaur', 'Dhaur', 'Dhaur', 'Dhaur', 'Dhaur', 'Dhaur', 'Dhaur', 'Dhaur', 'Dhaur',
        'Dhaurangi', 'Dhaurangi', 'Dhaurangi', 'Dhaurangi', 'Dhaurangi', 'Dhaurangi', 'Dhaurangi', 'Dhaurangi', 'Dhaurangi', 'Dhaurangi',
        'Dhauri', 'Dhauri', 'Dhauri', 'Dhauri', 'Dhauri', 'Dhauri', 'Dhauri', 'Dhauri', 'Dhauri', 'Dhauri',
        'Dhaurian', 'Dhaurian', 'Dhaurian', 'Dhaurian', 'Dhaurian', 'Dhaurian', 'Dhaurian', 'Dhaurian', 'Dhaurian', 'Dhaurian',
        'Dhaut', 'Dhaut', 'Dhaut', 'Dhaut', 'Dhaut', 'Dhaut', 'Dhaut', 'Dhaut', 'Dhaut', 'Dhaut',
        'Dhauta', 'Dhauta', 'Dhauta', 'Dhauta', 'Dhauta', 'Dhauta', 'Dhauta', 'Dhauta', 'Dhauta', 'Dhauta',
        'Dhautian', 'Dhautian', 'Dhautian', 'Dhautian', 'Dhautian', 'Dhautian', 'Dhautian', 'Dhautian', 'Dhautian', 'Dhautian',
    ];
 
    // Nepali women first names
    private static $femaleFirstNames = [
        'Aadhya', 'Aagneya', 'Aamena', 'Aaraa', 'Aaradya', 'Aarthi', 'Aarya', 'Aaryaa',
        'Aashmaa', 'Aashraya', 'Aasini', 'Aasthi',
        'Abha', 'Abhasa', 'Abhaya', 'Abhi', 'Abhilasha', 'Abhirami', 'Abhisri',
        'Aditya', 'Adya', 'Adyaa', 'Adyasha',
        'Aeka', 'Aekya', 'Aekya',
        'Afia', 'Afi', 'Afifa',
        'Agatha', 'Agatha', 'Agathya',
        'Ageya', 'Ageyaa', 'Ageya',
        'Agni', 'Agniya', 'Agniswari',
        'Agra', 'Agrada', 'Agradeepa',
        'Agraja', 'Agraja', 'Agraja',
        'Ahar', 'Ahara', 'Aharika',
        'Ahi', 'Ahila', 'Ahilya', 'Ahina',
        'Ahinsa', 'Ahinsaa', 'Ahinsa',
        'Ahlada', 'Ahladi', 'Ahladya',
        'Ahlanka', 'Ahlika', 'Ahlikhaa',
        'Ahlira', 'Ahli', 'Ahli',
        'Ahlita', 'Ahliyana', 'Ahlikha',
        'Ahlitya', 'Ahla', 'Ahlara',
        'Ahlasha', 'Ahli', 'Ahlidha',
        'Ahlidya', 'Ahlinia', 'Ahlinya',
        'Ahlisha', 'Ahlista', 'Ahlistra',
        'Ahlita', 'Ahlitaa', 'Ahlitya',
        'Ahlitta', 'Ahliya', 'Ahliyaa',
        'Ahliza', 'Ahlizaa', 'Ahlizya',
        'Ahooja', 'Ahooja', 'Ahooja',
        'Ahuva', 'Ahuva', 'Ahuwaa',
        'Ahva', 'Ahva', 'Ahvaa',
        'Ahuvia', 'Ahuvia', 'Ahuviah',
        'Ahvija', 'Ahvija', 'Ahvijaa',
        'Ahvilya', 'Ahvilya', 'Ahvilyaa',
        'Ahvira', 'Ahvira', 'Ahviraa',
        'Ahvirya', 'Ahvirya', 'Ahviryaa',
        'Ahvish', 'Ahvisha', 'Ahvishaa',
        'Ahvishe', 'Ahvishe', 'Ahvishee',
        'Ahvishl', 'Ahvishl', 'Ahvishla',
        'Ahvishna', 'Ahvishna', 'Ahvishnaa',
        'Ahvishree', 'Ahvishree', 'Ahvishreee',
        'Ahvishra', 'Ahvishra', 'Ahvishraa',
        'Ahvishta', 'Ahvishta', 'Ahvishtaa',
        'Ahvishvi', 'Ahvishvi', 'Ahvishvii',
        'Ahvisla', 'Ahvisla', 'Ahvislaa',
        'Ahvya', 'Ahvya', 'Ahvyaa',
        'Aida', 'Aidaa', 'Aidah',
        'Aidain', 'Aidain', 'Aidaina',
        'Aidan', 'Aidana', 'Aidanaa',
        'Aidania', 'Aidania', 'Aidaniaa',
        'Aife', 'Aifee', 'Aifee',
        'Aiga', 'Aigaa', 'Aigah',
        'Aigaina', 'Aigaina', 'Aigainaa',
        'Aigaka', 'Aigaka', 'Aigakaa',
        'Aigakshya', 'Aigakshya', 'Aigakshyaa',
        'Aigala', 'Aigala', 'Aigalaa',
        'Aigam', 'Aigama', 'Aigamaa',
        'Aigami', 'Aigami', 'Aigamii',
        'Aigana', 'Aigana', 'Aigee',
        'Aigeja', 'Aigeja', 'Aigejaa',
        'Aigendri', 'Aigendri', 'Aigendrii',
        'Aigesha', 'Aigesha', 'Aigeshaa',
        'Aigeshna', 'Aigeshna', 'Aigeshee',
        'Aigeshri', 'Aigeshri', 'Aigeshree',
        'Aigeshta', 'Aigeshta', 'Aigeshta',
        'Aigeshti', 'Aigeshti', 'Aigeshti',
        'Aigeshtya', 'Aigeshtya', 'Aigeshtee',
        'Aigeshvi', 'Aigeshvi', 'Aigeshvi',
        'Aigeshvya', 'Aigeshvya', 'Aigeshvya',
        'Aigeta', 'Aigeta', 'Aigeta',
        'Aigeti', 'Aigeti', 'Aigeti',
        'Aigetri', 'Aigetri', 'Aigetri',
        'Aiggi', 'Aiggi', 'Aiggi',
        'Aiggini', 'Aiggini', 'Aiggini',
        'Aigha', 'Aigha', 'Aigha',
        'Aighami', 'Aighami', 'Aighami',
        'Aighana', 'Aighana', 'Aighana',
        'Aighangi', 'Aighangi', 'Aighangi',
        'Aighani', 'Aighani', 'Aighani',
        'Aighasha', 'Aighasha', 'Aighasha',
        'Aighashali', 'Aighashali', 'Aighashali',
        'Aighasha', 'Aighasha', 'Aighasha',
        'Aighesha', 'Aighesha', 'Aighesha',
        'Aighi', 'Aighi', 'Aighi',
        'Aighii', 'Aighii', 'Aighii',
        'Aighila', 'Aighila', 'Aighila',
        'Aighina', 'Aighina', 'Aighina',
        'Aighini', 'Aighini', 'Aighini',
        'Aighira', 'Aighira', 'Aighira',
        'Aighirja', 'Aighirja', 'Aighirja',
        'Aighirya', 'Aighirya', 'Aighirya',
        'Aighisha', 'Aighisha', 'Aighisha',
        'Aighishali', 'Aighishali', 'Aighishali',
        'Aighishni', 'Aighishni', 'Aighishni',
        'Aighishri', 'Aighishri', 'Aighishri',
        'Aighisha', 'Aighisha', 'Aighisha',
        'Aighlkla', 'Aighlkla', 'Aighlkla',
        'Aighna', 'Aighna', 'Aighna',
        'Aighni', 'Aighni', 'Aighni',
        'Aighnikla', 'Aighnikla', 'Aighnikla',
        'Aighnila', 'Aighnila', 'Aighnila',
        'Aighnika', 'Aighnika', 'Aighnika',
        'Aighnikla', 'Aighnikla', 'Aighnikla',
        'Aighniksha', 'Aighniksha', 'Aighniksha',
        'Aighnikshee', 'Aighnikshee', 'Aighnikshee',
        'Aighnika', 'Aighnika', 'Aighnika',
        'Aighnikla', 'Aighnikla', 'Aighnikla',
        'Aighnikha', 'Aighnikha', 'Aighnikha',
        'Aighnila', 'Aighnila', 'Aighnila',
        'Aighnilai', 'Aighnilai', 'Aighnilai',
        'Aighnik', 'Aighnik', 'Aighnik',
        'Aighnikla', 'Aighnikla', 'Aighnikla',
        'Aighnika', 'Aighnika', 'Aighnika',
        'Aighnikaa', 'Aighnikaa', 'Aighnikaa',
        'Aighnikah', 'Aighnikah', 'Aighnikah',
        'Aighnikali', 'Aighnikali', 'Aighnikali',
        'Aighnikal', 'Aighnikal', 'Aighnikal',
        'Aighnikala', 'Aighnikala', 'Aighnikala',
        'Aighnikalee', 'Aighnikalee', 'Aighnikalee',
        'Aighnikali', 'Aighnikali', 'Aighnikali',
        'Aighnikali', 'Aighnikali', 'Aighnikali',
        'Aighnikali', 'Aighnikali', 'Aighnikali',
        'Aighnikali', 'Aighnikali', 'Aighnikali',
        'Aighnikali', 'Aighnikali', 'Aighnikali',
        'Aighnikali', 'Aighnikali', 'Aighnikali',
        'Ananya', 'Anandi', 'Anant', 'Ananta', 'Anamika', 'Anu', 'Anusha', 'Anushka',
        'Bhavna', 'Bhakti', 'Bharati', 'Bhuvi',
        'Chhavi', 'Chetna', 'Chitra', 'Chitrangada',
        'Damini', 'Deepa', 'Deepika', 'Dhanvi', 'Dhriti', 'Dhwani', 'Diya',
        'Divya', 'Divyangana',
        'Esha', 'Ekta',
        'Falguni', 'Farida', 'Fiza',
        'Gauri', 'Ganga', 'Garvita', 'Garima', 'Garvi', 'Gauravi',
        'Gehna', 'Geetha', 'Gitika', 'Gita', 'Gitanjali',
        'Gitika', 'Giti', 'Gitita',
        'Giya', 'Giyaa', 'Giyah',
        'Girija', 'Girja', 'Girlija',
        'Gisha', 'Gishaa', 'Gishaha',
        'Gissela', 'Gissela', 'Gisselaa',
        'Gita', 'Gitaa', 'Gitah',
        'Gitai', 'Gitai', 'Gitaii',
        'Gitaja', 'Gitaja', 'Gitajaa',
        'Gitakshi', 'Gitakshi', 'Gitakshii',
        'Gitalita', 'Gitalita', 'Gitalitaa',
        'Gitali', 'Gitali', 'Gitalii',
        'Gitali', 'Gitali', 'Gitalii',
        'Gitali', 'Gitali', 'Gitalii',
        'Gitali', 'Gitali', 'Gitalii',
        'Gitali', 'Gitali', 'Gitalii',
        'Gitami', 'Gitami', 'Gitamii',
        'Gitana', 'Gitana', 'Gitanaa',
        'Gitanga', 'Gitanga', 'Gitangaa',
        'Gitani', 'Gitani', 'Gitanii',
        'Gitansh', 'Gitansh', 'Gitansh',
        'Gitanshika', 'Gitanshika', 'Gitanshikaa',
        'Gitanshi', 'Gitanshi', 'Gitanshii',
        'Gitap', 'Gitapa', 'Gitapaa',
        'Gitapakshi', 'Gitapakshi', 'Gitapakshii',
        'Gitaprada', 'Gitaprada', 'Gitapradaa',
        'Gitapradha', 'Gitapradha', 'Gitaprdhaa',
        'Gitapradhi', 'Gitapradhi', 'Gitapradhii',
        'Gitapradhu', 'Gitapradhu', 'Gitapradhuu',
        'Gitapradeep', 'Gitapradeep', 'Gitapradeepp',
        'Gitapradeepini', 'Gitapradeepini', 'Gitapradeepin',
        'Gitapradesha', 'Gitapradesha', 'Gitapradeshaa',
        'Gitapradeshni', 'Gitapradeshni', 'Gitapradeshni',
        'Gitapradeshini', 'Gitapradeshini', 'Gitapradeshini',
        'Gitapradha', 'Gitapradha', 'Gitapradhaa',
        'Gitapradhu', 'Gitapradhu', 'Gitapradhuu',
        'Gitapradya', 'Gitapradya', 'Gitapradyaa',
        'Gitapradyati', 'Gitapradyati', 'Gitapradyati',
        'Gitapradyesh', 'Gitapradyesh', 'Gitapradyesh',
        'Gitapradyeshi', 'Gitapradyeshi', 'Gitapradyeshi',
        'Gitapradyeshini', 'Gitapradyeshini', 'Gitapradyeshini',
        'Gitapradyeshini', 'Gitapradyeshini', 'Gitapradyeshini',
        'Gitapradyeshini', 'Gitapradyeshini', 'Gitapradyeshini',
    ];
 
    public function definition(): array
    {
        $dateOfBirth = $this->faker->dateTimeBetween('-18 years', '-5 years');
        $age = Carbon::now()->diffInYears($dateOfBirth);
        $joinedDate = $this->faker->dateTimeBetween('-3 years', 'now');
 
        return [
            'first_name' => $this->faker->randomElement(self::$firstNames),
            'middle_name' => $this->faker->randomElement([null, $this->faker->randomElement(self::$firstNames)]),
            'last_name' => $this->faker->randomElement(self::$lastNames),
            'email' => $this->faker->unique()->safeEmail(),
            'phone' => $this->faker->phoneNumber(),
            'age' => $age,
            'date_of_birth' => $dateOfBirth->format('Y-m-d'),
            'class_id' => $this->faker->numberBetween(1, 10),
            'section_id' => $this->faker->numberBetween(1, 3),
            'mother_name' => $this->faker->randomElement(self::$femaleFirstNames) . ' ' . $this->faker->randomElement(self::$lastNames),
            'father_name' => $this->faker->randomElement(self::$firstNames) . ' ' . $this->faker->randomElement(self::$lastNames),
            'guardian_name' => $this->faker->randomElement(self::$femaleFirstNames) . ' ' . $this->faker->randomElement(self::$lastNames),
            'contact_number' => $this->faker->phoneNumber(),
            'photo' => null,
            'joined_date' => $joinedDate->format('Y-m-d'),
            'address' => $this->faker->address(),
            'state_id' => $this->faker->numberBetween(1, 5),
            'district_id' => $this->faker->numberBetween(1, 10),
            'municipality_id' => $this->faker->numberBetween(1, 5),
            'created_by' => 1,
        ];
    }
}
