export const VITE_API_STATES='api/getListOfStates'; 
export const  VITE_API_DISTRICTS='api/getListOfDistrictByStateId'
export const VITE_API_MUNICIPALITIES='api/getListOfMunicipalitiesByDistrictId' 
export const VITE_API_CLASSES='api/getClassesList'
export const VITE_API_SECTIONS='api/getSectionList'
export const VITE_API_STUDENTS='api/students'
export const VITE_API_STUDENTS_LIST_BY_DATE_RANGE='api/getStudentListByDateRange'
export const VITE_API_DELETE_STUDENT='api/deleteStudent'
export const VITE_API_UPDATE_STUDENT='api/updateStudent'
export const VITE_GET_GUARDIANS_LIST_BY_STUDENTID='api/guardian/getGuardiansByStudentId'
export const VITE_CREATE_GUARDIAN='api/guardian/createGuardian'
export const VITE_UPDATE_GUARDIANS_BY_GUARDIANID='api/guardian/updateGuardianByGuardianId'
export const VITE_DELETE_GUARDIANS_BY_GUARDIANID='api/guardian/deleteGuardianByGuardianId'
export const VITE_DISTRICT_LIST = 'get-districts-by-state_id';
export const VITE_MUNICIPALITY_LIST = 'get-municipalities-by-district_id';
export const VITE_SECTIONS_LIST_BY_CLASSID = 'get-sections-by-class_id';
export const VITE_STUDENT_LIST_BY_DATERANGE = 'get-students-by-date_range';
